# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hz < Formula
  desc ""
  homepage "https://github.com/dcilke/hz"
  version "0.3.0"

  on_macos do
    url "https://github.com/dcilke/hz/releases/download/v0.3.0/hz_0.3.0_darwin_all.tar.gz"
    sha256 "a6e6d897064f7ac3ea3928f36c5203c5f1c90d871191335a171b9fc36b382683"

    def install
      bin.install "hz"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dcilke/hz/releases/download/v0.3.0/hz_0.3.0_linux_amd64.tar.gz"
      sha256 "9553aec18848a5222eaea096d92b9b277214fe0eddabd0318f8f63476133e75b"

      def install
        bin.install "hz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcilke/hz/releases/download/v0.3.0/hz_0.3.0_linux_arm64.tar.gz"
      sha256 "35b9d4bac85ee1dfd611d43f344f45ed29ad94582602fc474b866fed4b88da1b"

      def install
        bin.install "hz"
      end
    end
  end
end
