# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hz < Formula
  desc ""
  homepage "https://github.com/dcilke/hz"
  version "0.2.1"

  on_macos do
    url "https://github.com/dcilke/hz/releases/download/v0.2.1/hz_0.2.1_darwin_all.tar.gz"
    sha256 "b19e010a26e55785d841903996ff23af4325dd817d21bb7d8232b00cdbb7c95d"

    def install
      bin.install "hz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcilke/hz/releases/download/v0.2.1/hz_0.2.1_linux_arm64.tar.gz"
      sha256 "e2726a0e1d2e1514ba035c2fd35f248c61b0c011280ca4bf2e94fc7025ac0578"

      def install
        bin.install "hz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dcilke/hz/releases/download/v0.2.1/hz_0.2.1_linux_amd64.tar.gz"
      sha256 "61f431de785ae3b37a8d4ef5e515721248999288079c6650dac9088a6a9a2961"

      def install
        bin.install "hz"
      end
    end
  end
end
